# Generated by Django 5.2.3 on 2025-07-13 00:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_user_avatar_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gameplayer',
            old_name='white_card_ids',
            new_name='card_hand',
        ),
        migrations.RemoveField(
            model_name='cardsubmission',
            name='white_card_id',
        ),
        migrations.RemoveField(
            model_name='cardsubmission',
            name='white_card_text',
        ),
        migrations.RemoveField(
            model_name='round',
            name='black_card_id',
        ),
        migrations.RemoveField(
            model_name='round',
            name='black_card_text',
        ),
        migrations.AddField(
            model_name='cardsubmission',
            name='white_cards',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='round',
            name='black_card',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='round',
            name='winning_submission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_round', to='main_app.cardsubmission'),
        ),
        migrations.AlterField(
            model_name='cardsubmission',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.gameplayer'),
        ),
        migrations.AlterField(
            model_name='gameplayer',
            name='turn_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='roommembership',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='main_app.room'),
        ),
    ]
