# Generated by Django 5.2.3 on 2025-07-15 16:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_roommembership_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='phase_start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
