# Generated by Django 5.2.3 on 2025-07-16 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_round_phase_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='dealt_white_cards',
            field=models.JSONField(default=list),
        ),
    ]
