# Generated by Django 5.2.3 on 2025-07-17 00:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_add_user_stats'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardPack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('card_count', models.IntegerField(default=0)),
                ('black_card_count', models.IntegerField(default=0)),
                ('white_card_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='room',
            name='selected_packs',
            field=models.ManyToManyField(blank=True, related_name='rooms', to='main_app.cardpack'),
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('card_type', models.CharField(choices=[('black', 'Black Card'), ('white', 'White Card')], max_length=5)),
                ('pick', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='main_app.cardpack')),
            ],
            options={
                'indexes': [models.Index(fields=['card_type', 'is_active'], name='main_app_ca_card_ty_69b6f7_idx'), models.Index(fields=['pack', 'card_type'], name='main_app_ca_pack_id_630f53_idx')],
                'unique_together': {('text', 'card_type', 'pack')},
            },
        ),
    ]
